export const SUPABASE_SEED_SQL = generateSeedSql();

insert into categories (slug, name, display_order)
values
  ('best-picture', 'Best Picture', 1),
  ('best-director', 'Best Director', 2),
  ('best-actor', 'Best Actor', 3),
  ('best-actress', 'Best Actress', 4),
  ('best-supporting-actor', 'Best Supporting Actor', 5),
  ('best-supporting-actress', 'Best Supporting Actress', 6),
  ('best-original-screenplay', 'Best Original Screenplay', 7),
  ('best-adapted-screenplay', 'Best Adapted Screenplay', 8),
  ('best-animated-feature-film', 'Best Animated Feature Film', 9),
  ('best-international-feature-film', 'Best International Feature Film', 10),
  ('best-documentary-feature-film', 'Best Documentary Feature Film', 11),
  ('best-original-score', 'Best Original Score', 12),
  ('best-original-song', 'Best Original Song', 13),
  ('best-cinematography', 'Best Cinematography', 14),
  ('best-film-editing', 'Best Film Editing', 15),
  ('best-production-design', 'Best Production Design', 16),
  ('best-costume-design', 'Best Costume Design', 17),
  ('best-makeup-and-hairstyling', 'Best Makeup and Hairstyling', 18),
  ('best-sound', 'Best Sound', 19),
  ('best-visual-effects', 'Best Visual Effects', 20),
  ('best-live-action-short-film', 'Best Live Action Short Film', 21),
  ('best-animated-short-film', 'Best Animated Short Film', 22),
  ('best-documentary-short-film', 'Best Documentary Short Film', 23),
  ('achievement-in-casting', 'Achievement in Casting', 24)
on conflict (slug) do update set
  name = excluded.name,
  display_order = excluded.display_order;

insert into nominees (category_id, label, short_label, display_order)
select c.id, v.label, v.short_label, v.display_order
from (
  values
    ('best-picture', 'Bugonia', 'Bugonia', 1),
    ('best-picture', 'F1', 'F1', 2),
    ('best-picture', 'Frankenstein', 'Frankenstein', 3),
    ('best-picture', 'Hamnet', 'Hamnet', 4),
    ('best-picture', 'Marty Supreme', 'Marty Supreme', 5),
    ('best-picture', 'One Battle after Another', 'One Battle after Another', 6),
    ('best-picture', 'The Secret Agent', 'The Secret Agent', 7),
    ('best-picture', 'Sentimental Value', 'Sentimental Value', 8),
    ('best-picture', 'Sinners', 'Sinners', 9),
    ('best-picture', 'Train Dreams', 'Train Dreams', 10),
    ('best-director', 'Hamnet', 'Hamnet', 1),
    ('best-director', 'Marty Supreme', 'Marty Supreme', 2),
    ('best-director', 'One Battle after Another', 'One Battle after Another', 3),
    ('best-director', 'Sentimental Value', 'Sentimental Value', 4),
    ('best-director', 'Sinners', 'Sinners', 5),
    ('best-actor', 'Timothée Chalamet — Marty Supreme', 'Timothée Chalamet — Marty Supreme', 1),
    ('best-actor', 'Leonardo DiCaprio — One Battle after Another', 'Leonardo DiCaprio — One Battle after Another', 2),    
    ('best-actor', 'Ethan Hawke — Blue Moon', 'Ethan Hawke — Blue Moon', 3),
    ('best-actor', 'Michael B. Jordan — Sinners', 'Michael B. Jordan — Sinners', 4),
    ('best-actor', 'Wagner Moura — The Secret Agent', 'Wagner Moura — The Secret Agent', 5),
    ('best-actress', 'Jessie Buckley — Hamnet', 'Jessie Buckley — Hamnet', 1),
    ('best-actress', 'Rose Byrne — If I Had Legs I''d Kick You', 'Rose Byrne — If I Had Legs I''d Kick You', 2),
    ('best-actress', 'Kate Hudson — Song Sung Blue', 'Kate Hudson — Song Sung Blue', 3),
    ('best-actress', 'Renate Reinsve — Sentimental Value', 'Renate Reinsve — Sentimental Value', 4),
    ('best-actress', 'Emma Stone — Bugonia', 'Emma Stone — Bugonia', 5),
    ('best-supporting-actor', 'Benicio Del Toro — One Battle after Another', 'Benicio Del Toro — One Battle after Another', 1),
    ('best-supporting-actor', 'Jacob Elordi — Frankenstein', 'Jacob Elordi — Frankenstein', 2),
    ('best-supporting-actor', 'Delroy Lindo — Sinners', 'Delroy Lindo — Sinners', 3),
    ('best-supporting-actor', 'Sean Penn — One Battle after Another', 'Sean Penn — One Battle after Another', 4),
    ('best-supporting-actor', 'Stellan Skarsgård — Sentimental Value', 'Stellan Skarsgård — Sentimental Value', 5),       
    ('best-supporting-actress', 'Elle Fanning — Sentimental Value', 'Elle Fanning — Sentimental Value', 1),
    ('best-supporting-actress', 'Inga Ibsdotter Lilleaas — Sentimental Value', 'Inga Ibsdotter Lilleaas — Sentimental Value', 2),
    ('best-supporting-actress', 'Amy Madigan — Weapons', 'Amy Madigan — Weapons', 3),
    ('best-supporting-actress', 'Wunmi Mosaku — Sinners', 'Wunmi Mosaku — Sinners', 4),
    ('best-supporting-actress', 'Teyana Taylor — One Battle after Another', 'Teyana Taylor — One Battle after Another', 5),
    ('best-original-screenplay', 'Blue Moon', 'Blue Moon', 1),
    ('best-original-screenplay', 'It Was Just an Accident', 'It Was Just an Accident', 2),
    ('best-original-screenplay', 'Marty Supreme', 'Marty Supreme', 3),
    ('best-original-screenplay', 'Sentimental Value', 'Sentimental Value', 4),
    ('best-original-screenplay', 'Sinners', 'Sinners', 5),
    ('best-adapted-screenplay', 'Bugonia', 'Bugonia', 1),
    ('best-adapted-screenplay', 'Frankenstein', 'Frankenstein', 2),
    ('best-adapted-screenplay', 'Hamnet', 'Hamnet', 3),
    ('best-adapted-screenplay', 'One Battle after Another', 'One Battle after Another', 4),
    ('best-adapted-screenplay', 'Train Dreams', 'Train Dreams', 5),
    ('best-animated-feature-film', 'Arco', 'Arco', 1),
    ('best-animated-feature-film', 'Elio', 'Elio', 2),
    ('best-animated-feature-film', 'KPop Demon Hunters', 'KPop Demon Hunters', 3),
    ('best-animated-feature-film', 'Little Amélie or the Character of Rain', 'Little Amélie or the Character of Rain', 4),
    ('best-animated-feature-film', 'Zootopia 2', 'Zootopia 2', 5),
    ('best-international-feature-film', 'The Secret Agent (Brazil)', 'The Secret Agent (Brazil)', 1),
    ('best-international-feature-film', 'It Was Just an Accident (France)', 'It Was Just an Accident (France)', 2),       
    ('best-international-feature-film', 'Sentimental Value (Norway)', 'Sentimental Value (Norway)', 3),
    ('best-international-feature-film', 'Sirāt (Spain)', 'Sirāt (Spain)', 4),
    ('best-international-feature-film', 'The Voice of Hind Rajab (Tunisia)', 'The Voice of Hind Rajab (Tunisia)', 5),     
    ('best-documentary-feature-film', 'The Alabama Solution', 'The Alabama Solution', 1),
    ('best-documentary-feature-film', 'Come See Me in the Good Light', 'Come See Me in the Good Light', 2),
    ('best-documentary-feature-film', 'Cutting through Rocks', 'Cutting through Rocks', 3),
    ('best-documentary-feature-film', 'Mr. Nobody against Putin', 'Mr. Nobody against Putin', 4),
    ('best-documentary-feature-film', 'The Perfect Neighbor', 'The Perfect Neighbor', 5),
    ('best-original-score', 'Bugonia', 'Bugonia', 1),
    ('best-original-score', 'Frankenstein', 'Frankenstein', 2),
    ('best-original-score', 'Hamnet', 'Hamnet', 3),
    ('best-original-score', 'One Battle after Another', 'One Battle after Another', 4),
    ('best-original-score', 'Sinners', 'Sinners', 5),
    ('best-original-song', 'Dear Me — Diane Warren: Relentless', 'Dear Me — Diane Warren: Relentless', 1),
    ('best-original-song', 'Golden — KPop Demon Hunters', 'Golden — KPop Demon Hunters', 2),
    ('best-original-song', 'I Lied To You — Sinners', 'I Lied To You — Sinners', 3),
    ('best-original-song', 'Sweet Dreams Of Joy — Viva Verdi!', 'Sweet Dreams Of Joy — Viva Verdi!', 4),
    ('best-original-song', 'Train Dreams — Train Dreams', 'Train Dreams — Train Dreams', 5),
    ('best-cinematography', 'Frankenstein', 'Frankenstein', 1),
    ('best-cinematography', 'Marty Supreme', 'Marty Supreme', 2),
    ('best-cinematography', 'One Battle after Another', 'One Battle after Another', 3),
    ('best-cinematography', 'Sinners', 'Sinners', 4),
    ('best-cinematography', 'Train Dreams', 'Train Dreams', 5),
    ('best-film-editing', 'F1', 'F1', 1),
    ('best-film-editing', 'Marty Supreme', 'Marty Supreme', 2),
    ('best-film-editing', 'One Battle after Another', 'One Battle after Another', 3),
    ('best-film-editing', 'Sentimental Value', 'Sentimental Value', 4),
    ('best-film-editing', 'Sinners', 'Sinners', 5),
    ('best-production-design', 'Frankenstein', 'Frankenstein', 1),
    ('best-production-design', 'Hamnet', 'Hamnet', 2),
    ('best-production-design', 'Marty Supreme', 'Marty Supreme', 3),
    ('best-production-design', 'One Battle after Another', 'One Battle after Another', 4),
    ('best-production-design', 'Sinners', 'Sinners', 5),
    ('best-costume-design', 'Avatar: Fire and Ash', 'Avatar: Fire and Ash', 1),
    ('best-costume-design', 'Frankenstein', 'Frankenstein', 2),
    ('best-costume-design', 'Hamnet', 'Hamnet', 3),
    ('best-costume-design', 'Marty Supreme', 'Marty Supreme', 4),
    ('best-costume-design', 'Sinners', 'Sinners', 5),
    ('best-makeup-and-hairstyling', 'Frankenstein', 'Frankenstein', 1),
    ('best-makeup-and-hairstyling', 'Kokuho', 'Kokuho', 2),
    ('best-makeup-and-hairstyling', 'Sinners', 'Sinners', 3),
    ('best-makeup-and-hairstyling', 'The Smashing Machine', 'The Smashing Machine', 4),
    ('best-makeup-and-hairstyling', 'The Ugly Stepsister', 'The Ugly Stepsister', 5),
    ('best-sound', 'F1', 'F1', 1),
    ('best-sound', 'Frankenstein', 'Frankenstein', 2),
    ('best-sound', 'One Battle after Another', 'One Battle after Another', 3),
    ('best-sound', 'Sinners', 'Sinners', 4),
    ('best-sound', 'Sirāt', 'Sirāt', 5),
    ('best-visual-effects', 'Avatar: Fire and Ash', 'Avatar: Fire and Ash', 1),
    ('best-visual-effects', 'F1', 'F1', 2),
    ('best-visual-effects', 'Jurassic World Rebirth', 'Jurassic World Rebirth', 3),
    ('best-visual-effects', 'The Lost Bus', 'The Lost Bus', 4),
    ('best-visual-effects', 'Sinners', 'Sinners', 5),
    ('best-live-action-short-film', 'Butcher''s Stain', 'Butcher''s Stain', 1),
    ('best-live-action-short-film', 'A Friend of Dorothy', 'A Friend of Dorothy', 2),
    ('best-live-action-short-film', 'Jane Austen''s Period Drama', 'Jane Austen''s Period Drama', 3),
    ('best-live-action-short-film', 'The Singers', 'The Singers', 4),
    ('best-live-action-short-film', 'Two People Exchanging Saliva', 'Two People Exchanging Saliva', 5),
    ('best-animated-short-film', 'Butterfly', 'Butterfly', 1),
    ('best-animated-short-film', 'Forevergreen', 'Forevergreen', 2),
    ('best-animated-short-film', 'The Girl Who Cried Pearls', 'The Girl Who Cried Pearls', 3),
    ('best-animated-short-film', 'Retirement Plan', 'Retirement Plan', 4),
    ('best-animated-short-film', 'The Three Sisters', 'The Three Sisters', 5),
    ('best-documentary-short-film', 'All the Empty Rooms', 'All the Empty Rooms', 1),
    ('best-documentary-short-film', 'Armed Only with a Camera: The Life and Death of Brent Renaud', 'Armed Only with a Camera: The Life and Death of Brent Renaud', 2),
    ('best-documentary-short-film', 'Children No More: "Were and Are Gone"', 'Children No More: "Were and Are Gone"', 3), 
    ('best-documentary-short-film', 'The Devil Is Busy', 'The Devil Is Busy', 4),
    ('best-documentary-short-film', 'Perfectly a Strangeness', 'Perfectly a Strangeness', 5),
    ('achievement-in-casting', 'Hamnet', 'Hamnet', 1),
    ('achievement-in-casting', 'Marty Supreme', 'Marty Supreme', 2),
    ('achievement-in-casting', 'One Battle after Another', 'One Battle after Another', 3),
    ('achievement-in-casting', 'The Secret Agent', 'The Secret Agent', 4),
    ('achievement-in-casting', 'Sinners', 'Sinners', 5)
) as v(category_slug, label, short_label, display_order)
join categories c on c.slug = v.category_slug
where not exists (
  select 1 from nominees n where n.category_id = c.id and n.label = v.label
);